apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "chernobyl"
  description: "test-react-ssr"
  annotations:
    github.com/project-slug: backstage-testing-bip/chernobyl
    backstage.io/techdocs-ref: url:https://github.com/backstage-testing-bip/chernobyl
spec:
  type: service
  lifecycle: experimental
  owner: "backstage-testing-bip"
